### ISSUE TITLE
Rest example

### ISSUE THREAD

**Issue by AbrahamAlcaina** [romanb/wai-route#6]
Hello, I'm new on Haskell and I'm trying to route a  simple Rest example. 
Could you provide me an example of how distinguish the HTTP verbs in the routes?

BTW my actual code
```Haskell
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Network.HTTP.Types
import Network.Wai
import Network.Wai.Handler.Warp (run)

app :: Application
app req respond = do
    putStrLn "I've done some IO here"
    respond $ responseLBS
        status200
        [("Content-Type", "text/plain")]
        "Hello, Web!"

main :: IO ()
main = do
    putStrLn "http://localhost:8080/"
    run 8080 app
```

**Comment by romanb** [comment]
Hello,

I assume you've already seen the [small sample](https://github.com/romanb/wai-route/blob/master/sample/Main.hs). This library itself only does routing based on paths, with optional variable capture, which is usually the very first step in routing requests to handlers. Once a handler has been chosen based on the request path, you can perform additional routing / branching based on inspecting the request further. For example, to branch based on the request method, you can simply inspect the `Request` passed to your handler function, e.g. extending the sample code:

```Haskell
bazHandler p rq k = case parseMethod (requestMethod rq) of
    Right GET -> k $ responseLBS status200 []
                   $ maybe L.empty L.fromStrict (lookup "baz" p)
    _ -> k $ responseLBS status405 [] L.empty
```

If your needs are basic, this approach can be sufficient. If you are interested in libraries that come with a lot more batteries included, you may be interested in one of [scotty](http://hackage.haskell.org/package/scotty), [wai-routing](http://hackage.haskell.org/package/wai-routing) (which is built on top of this library) or [servant](http://hackage.haskell.org/package/servant) but beware that the latter two employ some advanced features of Haskell's type system and may thus have a steep learning curve if you're just starting out.

**Comment by AbrahamAlcaina** [comment]
Thank you @romanb for your advice. I'll investigate wai-routing/Scotty
